# Generated by Django 4.2.6 on 2023-11-03 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="dste_joined",
            new_name="date_joined",
        ),
    ]
